const TOKEN_BUCKET_LIMIT = Number(process.env.TOKEN_BUCKET_LIMIT) || 5;
const TOKEN_BUCKET_INTERVAL = Number(process.env.TOKEN_BUCKET_INTERVAL) || 60;

const LEAKY_BUCKET_CAPACITY = Number(process.env.LEAKY_BUCKET_CAPACITY) || 5;
const LEAKY_BUCKET_LEAK_RATE = Number(process.env.LEAKY_BUCKET_LEAK_RATE) || 1;

export {
  TOKEN_BUCKET_LIMIT,
  TOKEN_BUCKET_INTERVAL,
  LEAKY_BUCKET_CAPACITY,
  LEAKY_BUCKET_LEAK_RATE,
};
